
FROM ubuntu:20.04
RUN apt update && apt install rsyslog -y
ENV TZ="Asia/Jakarta"
RUN echo '$ModLoad imudp \n\
$UDPServerRun 514 \n\
$ModLoad imtcp \n\
$InputTCPServerRun 514 \n\
$template RemoteStore, "/var/log/remote/%$year%/%$Month%/%$Day%/%$Hour%.log" \n\
:source, !isequal, "localhost" -?RemoteStore \n\
:source, isequal, "last" ~ ' > /etc/rsyslog.conf

EXPOSE 514

ENTRYPOINT ["rsyslogd", "-n"]